######################################################################
# Automatically generated by qmake (3.1) Mon Jan 22 23:35:05 2018
######################################################################

TEMPLATE = app
TARGET = GeminiCryptoTrader
INCLUDEPATH += .
TEMPLATE = app
TARGET = GeminiCryptoTrader
INCLUDEPATH += .
QT += core widgets gui
OBJECTS_DIR = ./obj
MOC_DIR = ./moc
UI_DIR = ./src
CONFIG += debug

# Input
HEADERS += src/MainWindow.h
FORMS += src/MainWindow.ui
SOURCES += src/Main.cpp src/MainWindow.cpp
