# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ConditionalDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConditionalDialog(object):
    def setupUi(self, ConditionalDialog):
        ConditionalDialog.setObjectName("ConditionalDialog")
        ConditionalDialog.resize(240, 240)
        ConditionalDialog.setMinimumSize(QtCore.QSize(240, 240))
        ConditionalDialog.setMaximumSize(QtCore.QSize(240, 240))
        self.gridLayout = QtWidgets.QGridLayout(ConditionalDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buyRB = QtWidgets.QRadioButton(ConditionalDialog)
        self.buyRB.setChecked(True)
        self.buyRB.setObjectName("buyRB")
        self.buttonGroup = QtWidgets.QButtonGroup(ConditionalDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.buyRB)
        self.horizontalLayout.addWidget(self.buyRB)
        self.sellRB = QtWidgets.QRadioButton(ConditionalDialog)
        self.sellRB.setObjectName("sellRB")
        self.buttonGroup.addButton(self.sellRB)
        self.horizontalLayout.addWidget(self.sellRB)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btcRB = QtWidgets.QRadioButton(ConditionalDialog)
        self.btcRB.setChecked(True)
        self.btcRB.setObjectName("btcRB")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(ConditionalDialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.btcRB)
        self.horizontalLayout_2.addWidget(self.btcRB)
        self.ethRB = QtWidgets.QRadioButton(ConditionalDialog)
        self.ethRB.setObjectName("ethRB")
        self.buttonGroup_2.addButton(self.ethRB)
        self.horizontalLayout_2.addWidget(self.ethRB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ConditionalDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.priceLE = QtWidgets.QLineEdit(ConditionalDialog)
        self.priceLE.setObjectName("priceLE")
        self.horizontalLayout_5.addWidget(self.priceLE)
        self.priceUnitLabel = QtWidgets.QLabel(ConditionalDialog)
        self.priceUnitLabel.setObjectName("priceUnitLabel")
        self.horizontalLayout_5.addWidget(self.priceUnitLabel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(ConditionalDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.amountLE = QtWidgets.QLineEdit(ConditionalDialog)
        self.amountLE.setObjectName("amountLE")
        self.horizontalLayout_3.addWidget(self.amountLE)
        self.amountUnitLabel = QtWidgets.QLabel(ConditionalDialog)
        self.amountUnitLabel.setObjectName("amountUnitLabel")
        self.horizontalLayout_3.addWidget(self.amountUnitLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.cancelButton = QtWidgets.QPushButton(ConditionalDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_4.addWidget(self.cancelButton)
        self.okButton = QtWidgets.QPushButton(ConditionalDialog)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_4.addWidget(self.okButton)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)

        self.retranslateUi(ConditionalDialog)
        QtCore.QMetaObject.connectSlotsByName(ConditionalDialog)

    def retranslateUi(self, ConditionalDialog):
        _translate = QtCore.QCoreApplication.translate
        ConditionalDialog.setWindowTitle(_translate("ConditionalDialog", "Conditional Order"))
        self.buyRB.setText(_translate("ConditionalDialog", "Bu&y"))
        self.sellRB.setText(_translate("ConditionalDialog", "Se&ll"))
        self.btcRB.setText(_translate("ConditionalDialog", "B&TC"))
        self.ethRB.setText(_translate("ConditionalDialog", "E&TH"))
        self.label.setText(_translate("ConditionalDialog", "If price is:"))
        self.priceUnitLabel.setText(_translate("ConditionalDialog", "USD"))
        self.label_2.setText(_translate("ConditionalDialog", "Amount:"))
        self.amountUnitLabel.setText(_translate("ConditionalDialog", "USD"))
        self.cancelButton.setText(_translate("ConditionalDialog", "&Cancel"))
        self.okButton.setText(_translate("ConditionalDialog", "&Ok"))

