# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 360)
        MainWindow.setMinimumSize(QtCore.QSize(640, 360))
        MainWindow.setMaximumSize(QtCore.QSize(640, 360))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.balanceGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.balanceGroupBox.sizePolicy().hasHeightForWidth())
        self.balanceGroupBox.setSizePolicy(sizePolicy)
        self.balanceGroupBox.setObjectName("balanceGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.balanceGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.balanceGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.accountBalanceLabel = QtWidgets.QLabel(self.balanceGroupBox)
        self.accountBalanceLabel.setObjectName("accountBalanceLabel")
        self.gridLayout.addWidget(self.accountBalanceLabel, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.balanceGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.btcBalanceLabel = QtWidgets.QLabel(self.balanceGroupBox)
        self.btcBalanceLabel.setObjectName("btcBalanceLabel")
        self.gridLayout.addWidget(self.btcBalanceLabel, 1, 1, 1, 1)
        self.ethBalanceLabel = QtWidgets.QLabel(self.balanceGroupBox)
        self.ethBalanceLabel.setObjectName("ethBalanceLabel")
        self.gridLayout.addWidget(self.ethBalanceLabel, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.balanceGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.balanceGroupBox)
        self.availableGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.availableGroupBox.sizePolicy().hasHeightForWidth())
        self.availableGroupBox.setSizePolicy(sizePolicy)
        self.availableGroupBox.setObjectName("availableGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.availableGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.usdAvailableLabel = QtWidgets.QLabel(self.availableGroupBox)
        self.usdAvailableLabel.setObjectName("usdAvailableLabel")
        self.gridLayout_2.addWidget(self.usdAvailableLabel, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.availableGroupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.btcAvailableLabel = QtWidgets.QLabel(self.availableGroupBox)
        self.btcAvailableLabel.setObjectName("btcAvailableLabel")
        self.gridLayout_2.addWidget(self.btcAvailableLabel, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.availableGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.availableGroupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.ethAvailableLabel = QtWidgets.QLabel(self.availableGroupBox)
        self.ethAvailableLabel.setObjectName("ethAvailableLabel")
        self.gridLayout_2.addWidget(self.ethAvailableLabel, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.availableGroupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.disconnectButton = QtWidgets.QPushButton(self.centralwidget)
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout.addWidget(self.disconnectButton)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout.addWidget(self.connectButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.currencyTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currencyTabWidget.sizePolicy().hasHeightForWidth())
        self.currencyTabWidget.setSizePolicy(sizePolicy)
        self.currencyTabWidget.setObjectName("currencyTabWidget")
        self.btcTab = QtWidgets.QWidget()
        self.btcTab.setObjectName("btcTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.btcTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_7 = QtWidgets.QLabel(self.btcTab)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.btcLastPriceLabel = QtWidgets.QLabel(self.btcTab)
        self.btcLastPriceLabel.setObjectName("btcLastPriceLabel")
        self.gridLayout_3.addWidget(self.btcLastPriceLabel, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.btcTab)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.btcDeltaLabel = QtWidgets.QLabel(self.btcTab)
        self.btcDeltaLabel.setObjectName("btcDeltaLabel")
        self.gridLayout_3.addWidget(self.btcDeltaLabel, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.btcTab)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.btcRangeLabel = QtWidgets.QLabel(self.btcTab)
        self.btcRangeLabel.setObjectName("btcRangeLabel")
        self.gridLayout_3.addWidget(self.btcRangeLabel, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.btcGraphView = QtWidgets.QGraphicsView(self.btcTab)
        self.btcGraphView.setObjectName("btcGraphView")
        self.gridLayout_4.addWidget(self.btcGraphView, 1, 0, 1, 1)
        self.currencyTabWidget.addTab(self.btcTab, "")
        self.ethTab = QtWidgets.QWidget()
        self.ethTab.setObjectName("ethTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.ethTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ethLastPriceLabel = QtWidgets.QLabel(self.ethTab)
        self.ethLastPriceLabel.setObjectName("ethLastPriceLabel")
        self.gridLayout_5.addWidget(self.ethLastPriceLabel, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.ethTab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.ethTab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 1, 0, 1, 1)
        self.ethDeltaLabel = QtWidgets.QLabel(self.ethTab)
        self.ethDeltaLabel.setObjectName("ethDeltaLabel")
        self.gridLayout_5.addWidget(self.ethDeltaLabel, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.ethTab)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.ethRangeLabel = QtWidgets.QLabel(self.ethTab)
        self.ethRangeLabel.setObjectName("ethRangeLabel")
        self.gridLayout_5.addWidget(self.ethRangeLabel, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 2, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.ethGraphView = QtWidgets.QGraphicsView(self.ethTab)
        self.ethGraphView.setObjectName("ethGraphView")
        self.gridLayout_6.addWidget(self.ethGraphView, 1, 0, 1, 1)
        self.currencyTabWidget.addTab(self.ethTab, "")
        self.gridLayout_7.addWidget(self.currencyTabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_Edit = QtWidgets.QAction(MainWindow)
        self.action_Edit.setObjectName("action_Edit")
        self.setupAction = QtWidgets.QAction(MainWindow)
        self.setupAction.setObjectName("setupAction")
        self.buyAction = QtWidgets.QAction(MainWindow)
        self.buyAction.setObjectName("buyAction")
        self.sellAction = QtWidgets.QAction(MainWindow)
        self.sellAction.setObjectName("sellAction")
        self.conditionalAction = QtWidgets.QAction(MainWindow)
        self.conditionalAction.setObjectName("conditionalAction")
        self.genDepositAction = QtWidgets.QAction(MainWindow)
        self.genDepositAction.setObjectName("genDepositAction")
        self.withdrawToAction = QtWidgets.QAction(MainWindow)
        self.withdrawToAction.setObjectName("withdrawToAction")
        self.exitAction = QtWidgets.QAction(MainWindow)
        self.exitAction.setObjectName("exitAction")
        self.optionsAction = QtWidgets.QAction(MainWindow)
        self.optionsAction.setObjectName("optionsAction")
        self.notificationsAction = QtWidgets.QAction(MainWindow)
        self.notificationsAction.setObjectName("notificationsAction")
        self.hideStatusbarAction = QtWidgets.QAction(MainWindow)
        self.hideStatusbarAction.setObjectName("hideStatusbarAction")
        self.showOrderbookAction = QtWidgets.QAction(MainWindow)
        self.showOrderbookAction.setObjectName("showOrderbookAction")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Visit_Gemini_API_Docs = QtWidgets.QAction(MainWindow)
        self.action_Visit_Gemini_API_Docs.setObjectName("action_Visit_Gemini_API_Docs")
        self.action_Gemini_Exchange = QtWidgets.QAction(MainWindow)
        self.action_Gemini_Exchange.setObjectName("action_Gemini_Exchange")
        self.menuFile.addAction(self.setupAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.buyAction)
        self.menuFile.addAction(self.sellAction)
        self.menuFile.addAction(self.conditionalAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.genDepositAction)
        self.menuFile.addAction(self.withdrawToAction)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exitAction)
        self.menuEdit.addAction(self.optionsAction)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.notificationsAction)
        self.menuView.addAction(self.hideStatusbarAction)
        self.menuView.addAction(self.showOrderbookAction)
        self.menuHelp.addAction(self.action_About)
        self.menuHelp.addAction(self.action_Visit_Gemini_API_Docs)
        self.menuHelp.addAction(self.action_Gemini_Exchange)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.currencyTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gemini Crypto Trader"))
        self.balanceGroupBox.setTitle(_translate("MainWindow", "Balances:"))
        self.label.setText(_translate("MainWindow", "Account Balance:"))
        self.accountBalanceLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "ETH Balance:"))
        self.btcBalanceLabel.setText(_translate("MainWindow", "TextLabel"))
        self.ethBalanceLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "BTC Balance:"))
        self.availableGroupBox.setTitle(_translate("MainWindow", "Available for Trading:"))
        self.usdAvailableLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "BTC Available:"))
        self.btcAvailableLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "USD Available:"))
        self.label_6.setText(_translate("MainWindow", "ETH Available:"))
        self.ethAvailableLabel.setText(_translate("MainWindow", "TextLabel"))
        self.disconnectButton.setText(_translate("MainWindow", "&Disconnect"))
        self.connectButton.setText(_translate("MainWindow", "&Connect"))
        self.label_7.setText(_translate("MainWindow", "Last Price:"))
        self.btcLastPriceLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "24-Hour Δ:"))
        self.btcDeltaLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "24-Hour Range:"))
        self.btcRangeLabel.setText(_translate("MainWindow", "TextLabel"))
        self.currencyTabWidget.setTabText(self.currencyTabWidget.indexOf(self.btcTab), _translate("MainWindow", "BTC"))
        self.ethLastPriceLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Last Price:"))
        self.label_10.setText(_translate("MainWindow", "24-Hour Δ:"))
        self.ethDeltaLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "24-Hour Range:"))
        self.ethRangeLabel.setText(_translate("MainWindow", "TextLabel"))
        self.currencyTabWidget.setTabText(self.currencyTabWidget.indexOf(self.ethTab), _translate("MainWindow", "ETH"))
        self.menuFile.setTitle(_translate("MainWindow", "&File"))
        self.menuEdit.setTitle(_translate("MainWindow", "&Edit"))
        self.menuView.setTitle(_translate("MainWindow", "&View"))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help"))
        self.action_Edit.setText(_translate("MainWindow", "&Edit"))
        self.setupAction.setText(_translate("MainWindow", "Se&tup"))
        self.buyAction.setText(_translate("MainWindow", "&Buy"))
        self.sellAction.setText(_translate("MainWindow", "&Sell"))
        self.conditionalAction.setText(_translate("MainWindow", "&Conditional"))
        self.genDepositAction.setText(_translate("MainWindow", "&Generate Deposit Address"))
        self.withdrawToAction.setText(_translate("MainWindow", "&Withdraw To..."))
        self.exitAction.setText(_translate("MainWindow", "&Exit"))
        self.optionsAction.setText(_translate("MainWindow", "&Options"))
        self.notificationsAction.setText(_translate("MainWindow", "&Notifications"))
        self.hideStatusbarAction.setText(_translate("MainWindow", "&Hide Statusbar"))
        self.showOrderbookAction.setText(_translate("MainWindow", "&Show Orderbook"))
        self.action_About.setText(_translate("MainWindow", "&About"))
        self.action_Visit_Gemini_API_Docs.setText(_translate("MainWindow", "&Visit Gemini API Docs"))
        self.action_Gemini_Exchange.setText(_translate("MainWindow", "Visit &Gemini Exchange"))

