# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrderBookDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderBookDialog(object):
    def setupUi(self, OrderBookDialog):
        OrderBookDialog.setObjectName("OrderBookDialog")
        OrderBookDialog.resize(640, 480)
        OrderBookDialog.setMinimumSize(QtCore.QSize(640, 480))
        OrderBookDialog.setMaximumSize(QtCore.QSize(640, 480))
        self.gridLayout_2 = QtWidgets.QGridLayout(OrderBookDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.orderBookTabs = QtWidgets.QTabWidget(OrderBookDialog)
        self.orderBookTabs.setObjectName("orderBookTabs")
        self.btcusdTab = QtWidgets.QWidget()
        self.btcusdTab.setObjectName("btcusdTab")
        self.gridLayout = QtWidgets.QGridLayout(self.btcusdTab)
        self.gridLayout.setObjectName("gridLayout")
        self.btcusdTable = QtWidgets.QTableWidget(self.btcusdTab)
        self.btcusdTable.setDragDropOverwriteMode(False)
        self.btcusdTable.setShowGrid(False)
        self.btcusdTable.setGridStyle(QtCore.Qt.SolidLine)
        self.btcusdTable.setWordWrap(False)
        self.btcusdTable.setCornerButtonEnabled(False)
        self.btcusdTable.setColumnCount(4)
        self.btcusdTable.setObjectName("btcusdTable")
        self.btcusdTable.setRowCount(0)
        self.btcusdTable.horizontalHeader().setCascadingSectionResizes(True)
        self.btcusdTable.horizontalHeader().setDefaultSectionSize(147)
        self.btcusdTable.horizontalHeader().setHighlightSections(False)
        self.btcusdTable.horizontalHeader().setStretchLastSection(True)
        self.btcusdTable.verticalHeader().setVisible(False)
        self.btcusdTable.verticalHeader().setHighlightSections(True)
        self.btcusdTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.btcusdTable, 0, 0, 1, 1)
        self.orderBookTabs.addTab(self.btcusdTab, "")
        self.ethusdTab = QtWidgets.QWidget()
        self.ethusdTab.setObjectName("ethusdTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ethusdTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ethusdTable = QtWidgets.QTableWidget(self.ethusdTab)
        self.ethusdTable.setDragDropOverwriteMode(False)
        self.ethusdTable.setShowGrid(False)
        self.ethusdTable.setGridStyle(QtCore.Qt.SolidLine)
        self.ethusdTable.setWordWrap(False)
        self.ethusdTable.setCornerButtonEnabled(False)
        self.ethusdTable.setColumnCount(4)
        self.ethusdTable.setObjectName("ethusdTable")
        self.ethusdTable.setRowCount(0)
        self.ethusdTable.horizontalHeader().setCascadingSectionResizes(True)
        self.ethusdTable.horizontalHeader().setDefaultSectionSize(147)
        self.ethusdTable.horizontalHeader().setHighlightSections(False)
        self.ethusdTable.horizontalHeader().setStretchLastSection(True)
        self.ethusdTable.verticalHeader().setVisible(False)
        self.ethusdTable.verticalHeader().setHighlightSections(True)
        self.ethusdTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.ethusdTable, 0, 0, 1, 1)
        self.orderBookTabs.addTab(self.ethusdTab, "")
        self.ethbtcTab = QtWidgets.QWidget()
        self.ethbtcTab.setObjectName("ethbtcTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ethbtcTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ethbtcTable = QtWidgets.QTableWidget(self.ethbtcTab)
        self.ethbtcTable.setDragDropOverwriteMode(False)
        self.ethbtcTable.setShowGrid(False)
        self.ethbtcTable.setGridStyle(QtCore.Qt.SolidLine)
        self.ethbtcTable.setWordWrap(False)
        self.ethbtcTable.setCornerButtonEnabled(False)
        self.ethbtcTable.setColumnCount(4)
        self.ethbtcTable.setObjectName("ethbtcTable")
        self.ethbtcTable.setRowCount(0)
        self.ethbtcTable.horizontalHeader().setCascadingSectionResizes(True)
        self.ethbtcTable.horizontalHeader().setDefaultSectionSize(147)
        self.ethbtcTable.horizontalHeader().setHighlightSections(False)
        self.ethbtcTable.horizontalHeader().setStretchLastSection(True)
        self.ethbtcTable.verticalHeader().setVisible(False)
        self.ethbtcTable.verticalHeader().setHighlightSections(True)
        self.ethbtcTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_4.addWidget(self.ethbtcTable, 0, 0, 1, 1)
        self.orderBookTabs.addTab(self.ethbtcTab, "")
        self.verticalLayout.addWidget(self.orderBookTabs)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.closeButton = QtWidgets.QPushButton(OrderBookDialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(OrderBookDialog)
        self.orderBookTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OrderBookDialog)

    def retranslateUi(self, OrderBookDialog):
        _translate = QtCore.QCoreApplication.translate
        OrderBookDialog.setWindowTitle(_translate("OrderBookDialog", "Order Book"))
        self.orderBookTabs.setTabText(self.orderBookTabs.indexOf(self.btcusdTab), _translate("OrderBookDialog", "BTCUSD"))
        self.orderBookTabs.setTabText(self.orderBookTabs.indexOf(self.ethusdTab), _translate("OrderBookDialog", "ETHUSD"))
        self.orderBookTabs.setTabText(self.orderBookTabs.indexOf(self.ethbtcTab), _translate("OrderBookDialog", "ETHBTC"))
        self.closeButton.setText(_translate("OrderBookDialog", "&Close"))

