# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/SellDialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SellDialog(object):
    def setupUi(self, SellDialog):
        SellDialog.setObjectName("SellDialog")
        SellDialog.resize(380, 320)
        SellDialog.setMinimumSize(QtCore.QSize(380, 320))
        SellDialog.setMaximumSize(QtCore.QSize(380, 320))
        self.gridLayout = QtWidgets.QGridLayout(SellDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(SellDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.sellButton = QtWidgets.QPushButton(SellDialog)
        self.sellButton.setObjectName("sellButton")
        self.horizontalLayout.addWidget(self.sellButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.sellTabWidget = QtWidgets.QTabWidget(SellDialog)
        self.sellTabWidget.setObjectName("sellTabWidget")
        self.btcUsdTab = QtWidgets.QWidget()
        self.btcUsdTab.setObjectName("btcUsdTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.btcUsdTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.btcUsdTab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.btcUsdOrderTypeCB = QtWidgets.QComboBox(self.btcUsdTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btcUsdOrderTypeCB.sizePolicy().hasHeightForWidth())
        self.btcUsdOrderTypeCB.setSizePolicy(sizePolicy)
        self.btcUsdOrderTypeCB.setObjectName("btcUsdOrderTypeCB")
        self.btcUsdOrderTypeCB.addItem("")
        self.btcUsdOrderTypeCB.addItem("")
        self.btcUsdOrderTypeCB.addItem("")
        self.btcUsdOrderTypeCB.addItem("")
        self.btcUsdOrderTypeCB.addItem("")
        self.verticalLayout_2.addWidget(self.btcUsdOrderTypeCB)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.btcUsdTab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btcUsdPriceLE = QtWidgets.QLineEdit(self.btcUsdTab)
        self.btcUsdPriceLE.setObjectName("btcUsdPriceLE")
        self.horizontalLayout_4.addWidget(self.btcUsdPriceLE)
        self.label_7 = QtWidgets.QLabel(self.btcUsdTab)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.btcUsdTab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btcUsdQuantityLE = QtWidgets.QLineEdit(self.btcUsdTab)
        self.btcUsdQuantityLE.setObjectName("btcUsdQuantityLE")
        self.horizontalLayout_3.addWidget(self.btcUsdQuantityLE)
        self.label_6 = QtWidgets.QLabel(self.btcUsdTab)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_4 = QtWidgets.QLabel(self.btcUsdTab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btcUsdTotalLE = QtWidgets.QLineEdit(self.btcUsdTab)
        self.btcUsdTotalLE.setObjectName("btcUsdTotalLE")
        self.horizontalLayout_2.addWidget(self.btcUsdTotalLE)
        self.label_5 = QtWidgets.QLabel(self.btcUsdTab)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 1, 2, 1)
        self.btcUsdBreakdownGB = QtWidgets.QGroupBox(self.btcUsdTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btcUsdBreakdownGB.sizePolicy().hasHeightForWidth())
        self.btcUsdBreakdownGB.setSizePolicy(sizePolicy)
        self.btcUsdBreakdownGB.setObjectName("btcUsdBreakdownGB")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.btcUsdBreakdownGB)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_36 = QtWidgets.QLabel(self.btcUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_11.addWidget(self.label_36)
        self.label_38 = QtWidgets.QLabel(self.btcUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_11.addWidget(self.label_38)
        self.label_40 = QtWidgets.QLabel(self.btcUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_40.sizePolicy().hasHeightForWidth())
        self.label_40.setSizePolicy(sizePolicy)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_11.addWidget(self.label_40)
        self.gridLayout_6.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.btcUsdOrderLabel = QtWidgets.QLabel(self.btcUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btcUsdOrderLabel.sizePolicy().hasHeightForWidth())
        self.btcUsdOrderLabel.setSizePolicy(sizePolicy)
        self.btcUsdOrderLabel.setText("")
        self.btcUsdOrderLabel.setObjectName("btcUsdOrderLabel")
        self.verticalLayout_12.addWidget(self.btcUsdOrderLabel)
        self.btcUsdFeeLabel = QtWidgets.QLabel(self.btcUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btcUsdFeeLabel.sizePolicy().hasHeightForWidth())
        self.btcUsdFeeLabel.setSizePolicy(sizePolicy)
        self.btcUsdFeeLabel.setText("")
        self.btcUsdFeeLabel.setObjectName("btcUsdFeeLabel")
        self.verticalLayout_12.addWidget(self.btcUsdFeeLabel)
        self.btcUsdTotalLabel = QtWidgets.QLabel(self.btcUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btcUsdTotalLabel.sizePolicy().hasHeightForWidth())
        self.btcUsdTotalLabel.setSizePolicy(sizePolicy)
        self.btcUsdTotalLabel.setText("")
        self.btcUsdTotalLabel.setObjectName("btcUsdTotalLabel")
        self.verticalLayout_12.addWidget(self.btcUsdTotalLabel)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.btcUsdBreakdownGB, 1, 0, 1, 1)
        self.sellTabWidget.addTab(self.btcUsdTab, "")
        self.ethUsdTab = QtWidgets.QWidget()
        self.ethUsdTab.setObjectName("ethUsdTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ethUsdTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_22 = QtWidgets.QLabel(self.ethUsdTab)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.ethUsdOrderTypeCB = QtWidgets.QComboBox(self.ethUsdTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethUsdOrderTypeCB.sizePolicy().hasHeightForWidth())
        self.ethUsdOrderTypeCB.setSizePolicy(sizePolicy)
        self.ethUsdOrderTypeCB.setObjectName("ethUsdOrderTypeCB")
        self.ethUsdOrderTypeCB.addItem("")
        self.ethUsdOrderTypeCB.addItem("")
        self.ethUsdOrderTypeCB.addItem("")
        self.ethUsdOrderTypeCB.addItem("")
        self.ethUsdOrderTypeCB.addItem("")
        self.verticalLayout_7.addWidget(self.ethUsdOrderTypeCB)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_23 = QtWidgets.QLabel(self.ethUsdTab)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_8.addWidget(self.label_23)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ethUsdPriceLE = QtWidgets.QLineEdit(self.ethUsdTab)
        self.ethUsdPriceLE.setObjectName("ethUsdPriceLE")
        self.horizontalLayout_13.addWidget(self.ethUsdPriceLE)
        self.label_24 = QtWidgets.QLabel(self.ethUsdTab)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_13.addWidget(self.label_24)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.label_25 = QtWidgets.QLabel(self.ethUsdTab)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_8.addWidget(self.label_25)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ethUsdQuantityLE = QtWidgets.QLineEdit(self.ethUsdTab)
        self.ethUsdQuantityLE.setObjectName("ethUsdQuantityLE")
        self.horizontalLayout_14.addWidget(self.ethUsdQuantityLE)
        self.label_26 = QtWidgets.QLabel(self.ethUsdTab)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.label_27 = QtWidgets.QLabel(self.ethUsdTab)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_8.addWidget(self.label_27)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ethUsdTotalLE = QtWidgets.QLineEdit(self.ethUsdTab)
        self.ethUsdTotalLE.setObjectName("ethUsdTotalLE")
        self.horizontalLayout_15.addWidget(self.ethUsdTotalLE)
        self.label_28 = QtWidgets.QLabel(self.ethUsdTab)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_15.addWidget(self.label_28)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 0, 1, 2, 1)
        self.ethUsdBreakdownGB = QtWidgets.QGroupBox(self.ethUsdTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethUsdBreakdownGB.sizePolicy().hasHeightForWidth())
        self.ethUsdBreakdownGB.setSizePolicy(sizePolicy)
        self.ethUsdBreakdownGB.setObjectName("ethUsdBreakdownGB")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ethUsdBreakdownGB)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_42 = QtWidgets.QLabel(self.ethUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_42.sizePolicy().hasHeightForWidth())
        self.label_42.setSizePolicy(sizePolicy)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_13.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.ethUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_43.sizePolicy().hasHeightForWidth())
        self.label_43.setSizePolicy(sizePolicy)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_13.addWidget(self.label_43)
        self.label_44 = QtWidgets.QLabel(self.ethUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_13.addWidget(self.label_44)
        self.gridLayout_7.addLayout(self.verticalLayout_13, 0, 0, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.ethUsdOrderLabel = QtWidgets.QLabel(self.ethUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethUsdOrderLabel.sizePolicy().hasHeightForWidth())
        self.ethUsdOrderLabel.setSizePolicy(sizePolicy)
        self.ethUsdOrderLabel.setText("")
        self.ethUsdOrderLabel.setObjectName("ethUsdOrderLabel")
        self.verticalLayout_14.addWidget(self.ethUsdOrderLabel)
        self.ethUsdFeeLabel = QtWidgets.QLabel(self.ethUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethUsdFeeLabel.sizePolicy().hasHeightForWidth())
        self.ethUsdFeeLabel.setSizePolicy(sizePolicy)
        self.ethUsdFeeLabel.setText("")
        self.ethUsdFeeLabel.setObjectName("ethUsdFeeLabel")
        self.verticalLayout_14.addWidget(self.ethUsdFeeLabel)
        self.ethUsdTotalLabel = QtWidgets.QLabel(self.ethUsdBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethUsdTotalLabel.sizePolicy().hasHeightForWidth())
        self.ethUsdTotalLabel.setSizePolicy(sizePolicy)
        self.ethUsdTotalLabel.setText("")
        self.ethUsdTotalLabel.setObjectName("ethUsdTotalLabel")
        self.verticalLayout_14.addWidget(self.ethUsdTotalLabel)
        self.gridLayout_7.addLayout(self.verticalLayout_14, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.ethUsdBreakdownGB, 1, 0, 1, 1)
        self.sellTabWidget.addTab(self.ethUsdTab, "")
        self.ethBtcTab = QtWidgets.QWidget()
        self.ethBtcTab.setObjectName("ethBtcTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ethBtcTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_29 = QtWidgets.QLabel(self.ethBtcTab)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_9.addWidget(self.label_29)
        self.ethBtcOrderTypeCB = QtWidgets.QComboBox(self.ethBtcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethBtcOrderTypeCB.sizePolicy().hasHeightForWidth())
        self.ethBtcOrderTypeCB.setSizePolicy(sizePolicy)
        self.ethBtcOrderTypeCB.setObjectName("ethBtcOrderTypeCB")
        self.ethBtcOrderTypeCB.addItem("")
        self.ethBtcOrderTypeCB.addItem("")
        self.ethBtcOrderTypeCB.addItem("")
        self.ethBtcOrderTypeCB.addItem("")
        self.ethBtcOrderTypeCB.addItem("")
        self.verticalLayout_9.addWidget(self.ethBtcOrderTypeCB)
        self.gridLayout_5.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_30 = QtWidgets.QLabel(self.ethBtcTab)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_10.addWidget(self.label_30)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ethBtcPriceLE = QtWidgets.QLineEdit(self.ethBtcTab)
        self.ethBtcPriceLE.setObjectName("ethBtcPriceLE")
        self.horizontalLayout_16.addWidget(self.ethBtcPriceLE)
        self.label_31 = QtWidgets.QLabel(self.ethBtcTab)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_16.addWidget(self.label_31)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.label_32 = QtWidgets.QLabel(self.ethBtcTab)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_10.addWidget(self.label_32)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.ethBtcQuantityLE = QtWidgets.QLineEdit(self.ethBtcTab)
        self.ethBtcQuantityLE.setObjectName("ethBtcQuantityLE")
        self.horizontalLayout_17.addWidget(self.ethBtcQuantityLE)
        self.label_33 = QtWidgets.QLabel(self.ethBtcTab)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_17.addWidget(self.label_33)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.label_34 = QtWidgets.QLabel(self.ethBtcTab)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_10.addWidget(self.label_34)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.ethBtcTotalLE = QtWidgets.QLineEdit(self.ethBtcTab)
        self.ethBtcTotalLE.setObjectName("ethBtcTotalLE")
        self.horizontalLayout_18.addWidget(self.ethBtcTotalLE)
        self.label_35 = QtWidgets.QLabel(self.ethBtcTab)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_18.addWidget(self.label_35)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.gridLayout_5.addLayout(self.verticalLayout_10, 0, 1, 2, 1)
        self.ethBtcBreakdownGB = QtWidgets.QGroupBox(self.ethBtcTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethBtcBreakdownGB.sizePolicy().hasHeightForWidth())
        self.ethBtcBreakdownGB.setSizePolicy(sizePolicy)
        self.ethBtcBreakdownGB.setObjectName("ethBtcBreakdownGB")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.ethBtcBreakdownGB)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_48 = QtWidgets.QLabel(self.ethBtcBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_48.sizePolicy().hasHeightForWidth())
        self.label_48.setSizePolicy(sizePolicy)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_15.addWidget(self.label_48)
        self.label_49 = QtWidgets.QLabel(self.ethBtcBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_49.sizePolicy().hasHeightForWidth())
        self.label_49.setSizePolicy(sizePolicy)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_15.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.ethBtcBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_50.sizePolicy().hasHeightForWidth())
        self.label_50.setSizePolicy(sizePolicy)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_15.addWidget(self.label_50)
        self.gridLayout_8.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ethBtcOrderLabel = QtWidgets.QLabel(self.ethBtcBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethBtcOrderLabel.sizePolicy().hasHeightForWidth())
        self.ethBtcOrderLabel.setSizePolicy(sizePolicy)
        self.ethBtcOrderLabel.setText("")
        self.ethBtcOrderLabel.setObjectName("ethBtcOrderLabel")
        self.verticalLayout_16.addWidget(self.ethBtcOrderLabel)
        self.ethBtcFeeLabel = QtWidgets.QLabel(self.ethBtcBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethBtcFeeLabel.sizePolicy().hasHeightForWidth())
        self.ethBtcFeeLabel.setSizePolicy(sizePolicy)
        self.ethBtcFeeLabel.setText("")
        self.ethBtcFeeLabel.setObjectName("ethBtcFeeLabel")
        self.verticalLayout_16.addWidget(self.ethBtcFeeLabel)
        self.ethBtcTotalLabel = QtWidgets.QLabel(self.ethBtcBreakdownGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ethBtcTotalLabel.sizePolicy().hasHeightForWidth())
        self.ethBtcTotalLabel.setSizePolicy(sizePolicy)
        self.ethBtcTotalLabel.setText("")
        self.ethBtcTotalLabel.setObjectName("ethBtcTotalLabel")
        self.verticalLayout_16.addWidget(self.ethBtcTotalLabel)
        self.gridLayout_8.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.ethBtcBreakdownGB, 1, 0, 1, 1)
        self.sellTabWidget.addTab(self.ethBtcTab, "")
        self.gridLayout.addWidget(self.sellTabWidget, 0, 0, 1, 1)

        self.retranslateUi(SellDialog)
        self.sellTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SellDialog)

    def retranslateUi(self, SellDialog):
        _translate = QtCore.QCoreApplication.translate
        SellDialog.setWindowTitle(_translate("SellDialog", "Buy"))
        self.cancelButton.setText(_translate("SellDialog", "&Cancel"))
        self.sellButton.setText(_translate("SellDialog", "&Sell"))
        self.label.setText(_translate("SellDialog", "Order Type:"))
        self.btcUsdOrderTypeCB.setItemText(0, _translate("SellDialog", "Market"))
        self.btcUsdOrderTypeCB.setItemText(1, _translate("SellDialog", "Limit"))
        self.btcUsdOrderTypeCB.setItemText(2, _translate("SellDialog", "Auction-Only (AO) Limit"))
        self.btcUsdOrderTypeCB.setItemText(3, _translate("SellDialog", "Maker-or-Cancel (MOC)"))
        self.btcUsdOrderTypeCB.setItemText(4, _translate("SellDialog", "Immediate-or-Cancel (IOC)"))
        self.label_2.setText(_translate("SellDialog", "Price:"))
        self.label_7.setText(_translate("SellDialog", "USD"))
        self.label_3.setText(_translate("SellDialog", "Quantity:"))
        self.label_6.setText(_translate("SellDialog", "BTC"))
        self.label_4.setText(_translate("SellDialog", "Total:"))
        self.label_5.setText(_translate("SellDialog", "USD"))
        self.btcUsdBreakdownGB.setTitle(_translate("SellDialog", "Breakdown:"))
        self.label_36.setText(_translate("SellDialog", "Order:"))
        self.label_38.setText(_translate("SellDialog", "Fee:"))
        self.label_40.setText(_translate("SellDialog", "Total:"))
        self.sellTabWidget.setTabText(self.sellTabWidget.indexOf(self.btcUsdTab), _translate("SellDialog", "BTCUSD"))
        self.label_22.setText(_translate("SellDialog", "Order Type:"))
        self.ethUsdOrderTypeCB.setItemText(0, _translate("SellDialog", "Market"))
        self.ethUsdOrderTypeCB.setItemText(1, _translate("SellDialog", "Limit"))
        self.ethUsdOrderTypeCB.setItemText(2, _translate("SellDialog", "Auction-Only (AO) Limit"))
        self.ethUsdOrderTypeCB.setItemText(3, _translate("SellDialog", "Maker-or-Cancel (MOC)"))
        self.ethUsdOrderTypeCB.setItemText(4, _translate("SellDialog", "Immediate-or-Cancel (IOC)"))
        self.label_23.setText(_translate("SellDialog", "Price:"))
        self.label_24.setText(_translate("SellDialog", "USD"))
        self.label_25.setText(_translate("SellDialog", "Quantity:"))
        self.label_26.setText(_translate("SellDialog", "ETH"))
        self.label_27.setText(_translate("SellDialog", "Total:"))
        self.label_28.setText(_translate("SellDialog", "USD"))
        self.ethUsdBreakdownGB.setTitle(_translate("SellDialog", "Breakdown:"))
        self.label_42.setText(_translate("SellDialog", "Order:"))
        self.label_43.setText(_translate("SellDialog", "Fee:"))
        self.label_44.setText(_translate("SellDialog", "Total:"))
        self.sellTabWidget.setTabText(self.sellTabWidget.indexOf(self.ethUsdTab), _translate("SellDialog", "ETHUSD"))
        self.label_29.setText(_translate("SellDialog", "Order Type:"))
        self.ethBtcOrderTypeCB.setItemText(0, _translate("SellDialog", "Market"))
        self.ethBtcOrderTypeCB.setItemText(1, _translate("SellDialog", "Limit"))
        self.ethBtcOrderTypeCB.setItemText(2, _translate("SellDialog", "Auction-Only (AO) Limit"))
        self.ethBtcOrderTypeCB.setItemText(3, _translate("SellDialog", "Maker-or-Cancel (MOC)"))
        self.ethBtcOrderTypeCB.setItemText(4, _translate("SellDialog", "Immediate-or-Cancel (IOC)"))
        self.label_30.setText(_translate("SellDialog", "Price:"))
        self.label_31.setText(_translate("SellDialog", "BTC"))
        self.label_32.setText(_translate("SellDialog", "Quantity:"))
        self.label_33.setText(_translate("SellDialog", "ETH"))
        self.label_34.setText(_translate("SellDialog", "Total:"))
        self.label_35.setText(_translate("SellDialog", "BTC"))
        self.ethBtcBreakdownGB.setTitle(_translate("SellDialog", "Breakdown:"))
        self.label_48.setText(_translate("SellDialog", "Order:"))
        self.label_49.setText(_translate("SellDialog", "Fee:"))
        self.label_50.setText(_translate("SellDialog", "Total:"))
        self.sellTabWidget.setTabText(self.sellTabWidget.indexOf(self.ethBtcTab), _translate("SellDialog", "ETHBTC"))

